### ISSUE TITLE
Unavailable import

### ISSUE THREAD

**Issue by gcla** [lokicui/doc2vec-golang#2]
Hi again ;-) I tried the control script you have included, but it suggests there is a missing import - doc-sim-cal. I tried to clone that repo, but it doesn't seem to exist. Here's the error:

```
$ ./control build
traning Exec build ok
knn.go:7:5: cannot find package "github.com/lokicui/doc-sim-cal/utils" in any of:
        /home/gcla/source/go/src/github.com/lokicui/doc-sim-cal/utils (from $GOROOT)
        /home/gcla/go/src/github.com/lokicui/doc-sim-cal/utils (from $GOPATH)
build error
```

**Comment by lokicui** [comment]
I updated a version with jieba breaker as a default word breaker. You can download the latest version to see if there is still a problem
